### ISSUE TITLE
LinAlgError: Singular matrix

### ISSUE THREAD

**Issue by daniel-wrench** [fiddir/fBb#1]
Hi there - I am very interested in your 2020 paper and would appreciate being able to use this MFBB function. However, upon trying it on my own computer I get the following error: `LinAlgError: Singular matrix`. Many thanks.

**Comment by fiddir** [comment]
Hi Daniel,

thanks a lot for your interest in this package, it currently is in a very preliminary version, so I appreciate the feedback!

My guess is that the discrete points t_i in your case might start from t_0=0, which would explain the singular matrix inversion.
I will try to address this in a future version of the code. Please note that as of now, only equidistant t_i can be handled.

I hope that helps!

Best,

Jan

On 24. Nov 2022, at 20:48, Daniel Wrench ***@***.***> wrote:


ACHTUNG! Diese E-Mail kommt von Extern! WARNING! This email originated off-campus.


Hi there - I am very interested in your 2020 paper and would appreciate being able to use this MFBB function. However, upon trying it on my own computer I get the following error: LinAlgError: Singular matrix. Many thanks.
