### ISSUE TITLE
data_gaps

### ISSUE THREAD

**Issue by fiddir** [fiddir/fBb#3]
Develop the functionality for non-equidistantly spaced data.

**Comment by daniel-wrench** [comment]
This looks great to me:
![image](https://user-images.githubusercontent.com/62724118/219836025-816ba03f-059d-4c1a-b46c-5c216f7449a3.png)

**Comment by fiddir** [comment]
Glad that this helped for now and I wish you a good continuation of your solar wind project!

Best,

Jan
